version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  transform:
    run: python:latest python analysis/transform.py output/input.csv
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/cohort.pickle

  compute_uptake_for_paper:
    run: python:latest python analysis/compute_uptake_for_paper.py
    needs: [transform]
    outputs:
      moderately_sensitive:
        cohort: output/*/cumulative_coverage/*/*/*.csv
