groups = {
    "immuno_group": "Patients with Immunosuppression",
    "ckd_group": "Patients with CKD",
    "ast_group": "Patients with Asthma",
    "cns_group": "Patients with CNS Disease (including Stroke/TIA)",
    "resp_group": "Patients who have Chronic Respiratory Disease",
    "bmi_group": "Patients with Morbid Obesity",
    "diab_group": "Patients with Diabetes",
    "sevment_group": "Patients with Severe Mental Health",
    "atrisk_group": "Patients in Any Clinical Risk Group",
    "covax1d_group": "Patients who have received at least 1 dose of a COVID Vaccination",
    "covax2d_group": "Patients who have received at least 2 doses of a COVID Vaccination",
    "unstatvacc1_group": "Patients who have an unstated dose 1 vaccination type",
    "unstatvacc2_group": "Patients who have an unstated dose 2 vaccination type",
    "shield_group": "Patients who are shielding (High Risk from COVID-19)",
    "preg_group": "Patients who are pregnant",
}
